User.create([
  {name: 'Nicolas'},
  {name: 'Marju'},
  {name: 'Ed'},
  {name: 'Jo'},
  {name: 'Aliasgar'},
  {name: 'Ali'},
  {name: 'Bobby'},
  {name: 'Billie'},
  {name: 'Kay'},
  {name: 'Katy'},
  {name: 'Cam'},
  {name: 'Ciaran'}
])

Task.create([
  {text: 'Buy milk', priority: 'high', user_id: 1},
  {text: 'Buy milk', priority: 'high', user_id: 2},
  {text: 'Buy milk', priority: 'high', user_id: 3},
  {text: 'Buy milk', priority: 'high', user_id: 4},
  {text: 'Buy milk', priority: 'high', user_id: 5},
  {text: 'Buy milk', priority: 'high', user_id: 6},
  {text: 'Buy milk', priority: 'high', user_id: 7},
  {text: 'Buy milk', priority: 'high', user_id: 8},
  {text: 'Buy milk', priority: 'high', user_id: 9},
  {text: 'Buy milk', priority: 'high', user_id: 10},
  {text: 'Buy milk', priority: 'high', user_id: 11},
  {text: 'Buy milk', priority: 'high', user_id: 12},
  {text: 'Conquer the world', priority: 'high', user_id: 1},
  {text: 'Conquer the world', priority: 'high', user_id: 2},
  {text: 'Conquer the world', priority: 'high', user_id: 3},
  {text: 'Conquer the world', priority: 'high', user_id: 4},
  {text: 'Conquer the world', priority: 'high', user_id: 5},
  {text: 'Conquer the world', priority: 'high', user_id: 6},
  {text: 'Conquer the world', priority: 'high', user_id: 7},
  {text: 'Conquer the world', priority: 'high', user_id: 8},
  {text: 'Conquer the world', priority: 'high', user_id: 9},
  {text: 'Conquer the world', priority: 'high', user_id: 10},
  {text: 'Conquer the world', priority: 'high', user_id: 11},
  {text: 'Conquer the world', priority: 'high', user_id: 12}
])
